### ISSUE TITLE
I/O Error. /home/

### ISSUE THREAD

**Issue by annettek** [rcschaff82/cwp_2fa#1]
![screencapture-server-tabletworldstore-2083-cwp-d1fa07cc907e0e6a-tws-fileManager2-php-2020-02-29-17_47_06](https://user-images.githubusercontent.com/13532793/75602680-8ad9de00-5b1b-11ea-8550-d24d081dd898.png)
I/O Error.
/home/

was working

something must have chnaged

when trying to open file manager

**Comment by rcschaff82** [comment]
run the following command to fix the issue.
 sed -i 's@PHP_ADMIN_VALUE "@PHP_ADMIN_VALUE "open_basedir@' /usr/local/cwpsrv/conf.d/users/*

nginx -s reload


This issue has been fixed in the source code.

**Comment by annettek** [comment]
sorry but it still same error when i run the above this is what i get

[root@server ~]# sed -i 's@PHP_ADMIN_VALUE "@PHP_ADMIN_VALUE "open_basedir@' /usr/local/cwpsrv/conf.d/users/*
[root@server ~]# nginx -s reload
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/conf.d/hostname-ssl.conf:8
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/conf.d/vhosts/tabletworldstore.com.ssl.conf:8
[root@server ~]#


still same errror woud you like to see the server to look

also re installed it rebooted server still same error

**Comment by rcschaff82** [comment]
please post the contents of one of your .conf files in /usr/local/cwpsrv/conf.d/users/

**Comment by rcschaff82** [comment]
If you would like me to look at it, please add my Public Key to /root/.ssh/authorized_keys
Then send an email to rcschaff82[at]gmail with your IP address for the server for me to check out.

> `ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA4CqTLy9rKrmxeQOTlRWtE4u6uiwKKqzidaVtIPDMNVH8tMB1lME+vWQqmQLw6pgSLRtGrav63cC/2qNAO59GSMk70cw97ofsg55XGqMXS3yPM5MgjdMwWVI1407XFmyqjLzbFzcYXKSQNWhIbIb9MCE6pVm4a9AuUcMtcXrfoc1JBUWDZFYpYwvapQNTWYrsxpQ7IXrVf12WJ4xOxXn2is+XaeNWdtrs/LNZusWoECoBMJrv08qmCftky/mk2Is3jovZxlV7cU0/ygJBlnjnlDug0TLJECvy1skWbgLZNA23ZVrxtcOBKuxxsAF4V1At6c7kTkudjHENDlvvAw4MJw== rcschaff82_cwp2fa`

**Comment by annettek** [comment]
It easy to just send you details

 

[Removed Login Details]

**Comment by annettek** [comment]
Added key to file as well

 

ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA4CqTLy9rKrmxeQOTlRWtE4u6uiwKKqzidaVtIPDMNVH8tMB1lME+vWQqmQLw6pgSLRtGrav63cC/2qNAO59GSMk70cw97ofsg55XGqMXS3yPM5MgjdMwWVI1407XFmyqjLzbFzcYXKSQNWhIbIb9MCE6pVm4a9AuUcMtcXrfoc1JBUWDZFYpYwvapQNTWYrsxpQ7IXrVf12WJ4xOxXn2is+XaeNWdtrs/LNZusWoECoBMJrv08qmCftky/mk2Is3jovZxlV7cU0/ygJBlnjnlDug0TLJECvy1skWbgLZNA23ZVrxtcOBKuxxsAF4V1At6c7kTkudjHENDlvvAw4MJw== rcschaff82_cwp2fa

**Comment by rcschaff82** [comment]
I made corrections.   Try your user panel now.

**Comment by annettek** [comment]
Thanks so much for that 100% appericated

**Comment by rcschaff82** [comment]
You're Welcome

**Comment by annettek** [comment]
![screencapture-server-tabletworldstore-2083-cwp-c8da133747f9772a-tws-fileManager2-php-2020-03-13-20_24_40](https://user-images.githubusercontent.com/13532793/76607905-d901cf00-6568-11ea-9202-c949daab20c4.png)
ok the seerver just did and update now i cant login to server admin i just get this 404 not found error after eneter code
this is url that is left behind
https://server.tabletworldstore.com:2087/login/c93d0fc22f84f4914b8ce8bd12b55791.php

**Comment by annettek** [comment]
and now i noticed all my files are owned by 1000 not my account tws

this is caused by a cwp aupdate as i did the update like 10 mins before this happened

cwp are saying that the 2fa module is causing this. they did have a look but thats all they said

**Comment by rcschaff82** [comment]
I'm fairly sure that those issues aren't related to the mod, but CWP itself.  Nowhere in my mod do I chown any files, and the issue your seeing seems to be an issue with Nginx's rewrite, which I also don't modify.   Also, next time click "Reopen and comment", as my mail filters are set pretty high :)
