### ISSUE TITLE
Breaks Login Completely

### ISSUE THREAD

**Issue by rothkj1022** [rcschaff82/cwp_2fa#2]
I was able to follow the instructions to install the module, but before I decided to sign out and back in again to test the 2FA, I tried signing in through a second browser, in case it didn't work.  Glad I did, because the root login no longer works at all.  I never even get to the part where i enter in the code - I just get "login failed".  I even validated that I am not mistyping my password by logging in as root through ssh, pasting in the password.

I attempted to turn off 2FA through my still active root session, but I still get the same result.

My CWP version is 0.9.8.956.  Any suggestions?

**Comment by rcschaff82** [comment]
Please check /usr/local/cwpsrv/logs/error_log for any errors from php.

**Comment by rothkj1022** [comment]
Edited to remove my host name and ip:
2020/04/24 08:42:27 [error] 27535#0: *625 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: logout in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 27
PHP message: PHP Notice:  Undefined index: login in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 29
PHP message: PHP Notice:  Undefined index: fast_login in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 119" while reading response header from upstream, client: {ip}, server: localhost, request: "GET /login/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/local/cwp/php71/var/sockets/cwpsrv.sock:", host: "{hostname}:2087"
2020/04/24 08:42:38 [error] 27535#0: *625 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: logout in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 27
PHP message: PHP Notice:  Undefined index: login in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 29" while reading response header from upstream, client: {ip}, server: localhost, request: "POST /login/index.php? HTTP/1.1", upstream: "fastcgi://unix:/usr/local/cwp/php71/var/sockets/cwpsrv.sock:", host: "{hostname}:2087", referrer: "https://{hostname}:2087/login/index.php"
2020/04/24 08:42:38 [error] 27535#0: *625 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: logout in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 27
PHP message: PHP Notice:  Undefined index: fast_login in /usr/local/cwpsrv/htdocs/admin/login/index.php on line 119" while reading response header from upstream, client: {ip}, server: localhost, request: "GET /login/index.php?login=failed HTTP/1.1", upstream: "fastcgi://unix:/usr/local/cwp/php71/var/sockets/cwpsrv.sock:", host: "{hostname}:2087", referrer: "https://{hostname}:2087/login/index.php"

**Comment by rcschaff82** [comment]
Can you post /usr/local/cwpsrv/htdocs/admin/login/index.php   Something seems malformed.

**Comment by rothkj1022** [comment]
<?php
define("DO_LOGIN","f3db4c83f9fd3e958cc2b524f9a6a654.php");
$ct = "constant";
// Function for our template
function hd($param) {
    // just return whatever has been passed to us
    return $param;
}
$hd = "hd";
function fastlogin() {
global $ct;
$test = $ct('DO_LOGIN');
	header("Location: /login/$test" ,TRUE,307);
}
// Preset Variables / set to nothing if they don't exists (Prevent errors)
$fa2="";
$loginError="";
$userName = !empty($_POST['username'])?htmlentities($_POST['username'], ENT_QUOTES):"";
$userPasswd = !empty($_POST['password'])?htmlentities($_POST['password'], ENT_QUOTES):"";
$authCode = !empty($_POST['authCode'])?htmlentities($_POST['authCode'], ENT_QUOTES):"";
$commit = !empty($_POST['commit'])?htmlentities($_POST['commit'], ENT_QUOTES):"";
$passwdFile='/etc/shadow';
$users=file('/etc/shadow');

//Do the work ///
// Logout?  Redirect to old index page //
if ($_GET['logout'] == 'yes') header("Location: {$ct('DO_LOGIN')}?logout=yes");
//   Set our errors using switch //
switch($_GET['login']) {
 case "nousername":
	$loginError = "*Empty Username*";
	break;
 case "userlogin":
	$loginError = "This is admin area!!!<br>*<a href=\"https://".$_SERVER['SERVER_NAME'].":2083\">&gt; Login to NEW User Panel &lt;</a>*";
	break;
 case "nopassword":
	$loginError = "*Empty Password*";
	break;
 case "failed":
	$loginError = "*Login Failed*";
	break;
 case "logout":
	$loginError = "*You have logged out.*";
	break;
 case "invalidauth":
	$loginError = "*Invalid Auth Token*";
	break;
 default:
	$loginError = "";
}
//  Check our Post Data //
if (!empty($_POST)) {
//  No username, redirect //
if ($userName=="") {header("Location: index.php?login=nousername"); exit();}
// No Password Redirect //
if ($userPasswd==""){ header("Location: index.php?login=nopassword"); exit();}
// Check if username exists, if yes continue, otherwise show user login link //
if (!$user=preg_grep("/\b$userName\b/",$users)){header("Location: index.php?login=userlogin");}
// Check Password for User
list(,$passwdInDB)=explode(':',array_pop($user));
if (crypt($userPasswd,$passwdInDB) != $passwdInDB) {header("Location: index.php?login=failed");exit();}
//  Check Auth Code
if (file_exists("/root/.f2akey")) {
        $authKey = file_get_contents("/{$userName}/.f2akey");
        $fa2 = true;
} else {
	fastlogin();
	$fa2 = false;
}
require_once("design/googleAuthenticator.php");
$gauth = new GoogleAuthenticator();
if ($gauth->verifyCode(trim($authKey),$authCode) === true) {
	fastlogin();
	$fa2 = false;
} else {
	$loginError = ($authCode != "")?"*Invaid Auth* ":"";
}



}
echo <<< EOL
<!DOCTYPE html>



 <html lang="en"> 
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Login | CentOS WebPanel</title>
  <link rel="icon" href="design/img/ico/favicon.ico" type="image/png">
  <link rel="stylesheet" href="design/img/login.css">
  <style>
  .hide {
  visibility:hidden;
  position:absolute;
  }
  .show {
  visibility:show;
  position:relative;
  }
  </style>
  

</head>
<body>
  <section class="container">
    <div class="login">
      <img src="design/images/cwp_small.png">
      <h1>Login to CentOS WebPanel
	  <br>{$loginError}</h1>
      <form method="post" action="{$hd(($fa2 === false)?"{$ct('DO_LOGIN')}":"?")}">
	<fieldset id="main" class="{$hd(($userName != "")?"hide":"show")}">
        <p><input type="text" name="username" value="{$userName}" placeholder="Admin Username" autofocus></p>
        <p><input type="password" name="password" value="{$userPasswd}" placeholder="Admin Password"></p>
        <p class="remember_me">
          <label>
            <input type="checkbox" name="fast_login" id="fast_login" {$hd(($_POST['fast_login'] == 'on')?"checked=\"checked\"":"")}>
            Fast Login (no stats and checks)
          </label>
        </p>
	</fieldset>
	<fieldset id="2fa" class="{$hd(($fa2 == true)?"show":"hide")}">
	<p><input type="text" name="authCode" value="" placeholder="Auth Code" autofocus autocomplete="off"></p>
	<input type="hidden" name="commit" value="Login">
	</fieldset>
        <p class="submit"><input id="mesubmit" type="submit" name="commit" value="Login"></p>
      </form>
    </div>

    <div class="login-help">
       <p>You are using SSL login.</p>

    </div>
  </section>

  <section class="about">
    <p class="about-links">
      <a href="http://centos-webpanel.com" target="_parent">Visit Website</a>
      <a href="http://centos-webpanel.com/installation-instructions" target="_parent">How to Install</a>
    </p>
    <p class="about-author">
      &copy; 2020 <a href="http://centos-webpanel.com" target="_blank">CentOS WebPanel</a>
	  control panel for linux
{$hd(($fa2 === false)?"<script>document.getElementById('mesubmit').style.visibility = \"hidden\"; document.forms[0].submit();</script>":"")}

</body>
</html>
EOL;
unset($_POST);
?>

**Comment by rothkj1022** [comment]
`
    </div>
  </section>

  <section class="about">
    <p class="about-links">
      <a href="http://centos-webpanel.com" target="_parent">Visit Website</a>
      <a href="http://centos-webpanel.com/installation-instructions" target="_parent">How to Install</a>
    </p>
    <p class="about-author">
      &copy; 2020 <a href="http://centos-webpanel.com" target="_blank">CentOS WebPanel</a>
	  control panel for linux
{$hd(($fa2 === false)?"<script>document.getElementById('mesubmit').style.visibility = \"hidden\"; document.forms[0].submit();</script>":"")}

</body>
</html>
EOL;
unset($_POST);
?>`

**Comment by rcschaff82** [comment]
is f3db4c83f9fd3e958cc2b524f9a6a654.php the name of the other file in that directory?

**Comment by rothkj1022** [comment]
```
<?php
define("DO_LOGIN","f3db4c83f9fd3e958cc2b524f9a6a654.php");
$ct = "constant";
// Function for our template
function hd($param) {
    // just return whatever has been passed to us
    return $param;
}
$hd = "hd";
function fastlogin() {
global $ct;
$test = $ct('DO_LOGIN');
	header("Location: /login/$test" ,TRUE,307);
}
// Preset Variables / set to nothing if they don't exists (Prevent errors)
$fa2="";
$loginError="";
$userName = !empty($_POST['username'])?htmlentities($_POST['username'], ENT_QUOTES):"";
$userPasswd = !empty($_POST['password'])?htmlentities($_POST['password'], ENT_QUOTES):"";
$authCode = !empty($_POST['authCode'])?htmlentities($_POST['authCode'], ENT_QUOTES):"";
$commit = !empty($_POST['commit'])?htmlentities($_POST['commit'], ENT_QUOTES):"";
$passwdFile='/etc/shadow';
$users=file('/etc/shadow');

//Do the work ///
// Logout?  Redirect to old index page //
if ($_GET['logout'] == 'yes') header("Location: {$ct('DO_LOGIN')}?logout=yes");
//   Set our errors using switch //
switch($_GET['login']) {
 case "nousername":
	$loginError = "*Empty Username*";
	break;
 case "userlogin":
	$loginError = "This is admin area!!!<br>*<a href=\"https://".$_SERVER['SERVER_NAME'].":2083\">&gt; Login to NEW User Panel &lt;</a>*";
	break;
 case "nopassword":
	$loginError = "*Empty Password*";
	break;
 case "failed":
	$loginError = "*Login Failed*";
	break;
 case "logout":
	$loginError = "*You have logged out.*";
	break;
 case "invalidauth":
	$loginError = "*Invalid Auth Token*";
	break;
 default:
	$loginError = "";
}
//  Check our Post Data //
if (!empty($_POST)) {
//  No username, redirect //
if ($userName=="") {header("Location: index.php?login=nousername"); exit();}
// No Password Redirect //
if ($userPasswd==""){ header("Location: index.php?login=nopassword"); exit();}
// Check if username exists, if yes continue, otherwise show user login link //
if (!$user=preg_grep("/\b$userName\b/",$users)){header("Location: index.php?login=userlogin");}
// Check Password for User
list(,$passwdInDB)=explode(':',array_pop($user));
if (crypt($userPasswd,$passwdInDB) != $passwdInDB) {header("Location: index.php?login=failed");exit();}
//  Check Auth Code
if (file_exists("/root/.f2akey")) {
        $authKey = file_get_contents("/{$userName}/.f2akey");
        $fa2 = true;
} else {
	fastlogin();
	$fa2 = false;
}
require_once("design/googleAuthenticator.php");
$gauth = new GoogleAuthenticator();
if ($gauth->verifyCode(trim($authKey),$authCode) === true) {
	fastlogin();
	$fa2 = false;
} else {
	$loginError = ($authCode != "")?"*Invaid Auth* ":"";
}

}
echo <<< EOL
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Login | CentOS WebPanel</title>
  <link rel="icon" href="design/img/ico/favicon.ico" type="image/png">
  <link rel="stylesheet" href="design/img/login.css">
  <style>
  .hide {
  visibility:hidden;
  position:absolute;
  }
  .show {
  visibility:show;
  position:relative;
  }
  </style>
  <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--script src="design/js/jquery.min.js" type="text/javascript"></script><script src="design/js/login.js" type="text/javascript"></script-->
</head>
<body>
  <section class="container">
    <div class="login">
      <img src="design/images/cwp_small.png">
      <h1>Login to CentOS WebPanel
	  <br>{$loginError}</h1>
      <form method="post" action="{$hd(($fa2 === false)?"{$ct('DO_LOGIN')}":"?")}">
	<fieldset id="main" class="{$hd(($userName != "")?"hide":"show")}">
        <p><input type="text" name="username" value="{$userName}" placeholder="Admin Username" autofocus></p>
        <p><input type="password" name="password" value="{$userPasswd}" placeholder="Admin Password"></p>
        <p class="remember_me">
          <label>
            <input type="checkbox" name="fast_login" id="fast_login" {$hd(($_POST['fast_login'] == 'on')?"checked=\"checked\"":"")}>
            Fast Login (no stats and checks)
          </label>
        </p>
	</fieldset>
	<fieldset id="2fa" class="{$hd(($fa2 == true)?"show":"hide")}">
	<p><input type="text" name="authCode" value="" placeholder="Auth Code" autofocus autocomplete="off"></p>
	<input type="hidden" name="commit" value="Login">
	</fieldset>
        <p class="submit"><input id="mesubmit" type="submit" name="commit" value="Login"></p>
      </form>
    </div>

    <div class="login-help">
       <p>You are using SSL login.</p>

    </div>
  </section>

  <section class="about">
    <p class="about-links">
      <a href="http://centos-webpanel.com" target="_parent">Visit Website</a>
      <a href="http://centos-webpanel.com/installation-instructions" target="_parent">How to Install</a>
    </p>
    <p class="about-author">
      &copy; 2020 <a href="http://centos-webpanel.com" target="_blank">CentOS WebPanel</a>
	  control panel for linux
{$hd(($fa2 === false)?"<script>document.getElementById('mesubmit').style.visibility = \"hidden\"; document.forms[0].submit();</script>":"")}

</body>
</html>
EOL;
unset($_POST);
?>
```

**Comment by rothkj1022** [comment]
```
[root@{hostname} login]# ls -la
total 64
drwxr-xr-x 2 root root  4096 Apr 24 00:20 .
drwxr-xr-x 8 root root  4096 Apr 24 00:17 ..
lrwxrwxrwx 1 root root     9 Apr 24 00:17 design -> ../design
-rw-r----- 1 root root 40499 Aug 12  2019 f3db4c83f9fd3e958cc2b524f9a6a654.php
-rw-r--r-- 1 root root  5354 Apr 24 00:20 index.php
-rw-r--r-- 1 root root  5318 Apr 23 15:50 index_working.php
```

**Comment by rcschaff82** [comment]
Can you log in at all?  or only ssh?

**Comment by rcschaff82** [comment]
if you would rather chat, I'm on Google Hangouts.  rcschaff82@gmail.com

**Comment by rothkj1022** [comment]
> if you would rather chat, I'm on Google Hangouts. [rcschaff82@gmail.com](mailto:rcschaff82@gmail.com)

Invite sent.

**Comment by rothkj1022** [comment]
> Can you log in at all? or only ssh?

No, I cannot login through the CWP portal at all.  I still have an active session that I have not yet logged out of, so I am testing through a second browser.  I am able to login through ssh just fine.

**Comment by rcschaff82** [comment]
that could actually be the issue.  CWP does not allow multiple sessions.

**Comment by rcschaff82** [comment]
I take that back, was just able to do it.

**Comment by rcschaff82** [comment]
Special Characters in password failed validation.  Fixed in latest code..
