### ISSUE TITLE
updates in original them

### ISSUE THREAD

**Issue by webservicebe** [rcschaff82/cwp_2fa#3]
It seems that the code of the original theme is changed.
Now when you access the Reseller-Manage item you got an error, see https://bugs.control-webpanel.com/view.php?id=102.
Maybe do a check of the themes also?
upon change: rsync -azvp original/ modified/, followed by a copy of mod_user2fa.html, menu_left.html and js/modules/user2fa.js.twig.

**Comment by rcschaff82** [comment]
Thank you for bringing this to my attention.  I have added the rsync to the watch.sh script to monitor updates.  Giving you credit of course.
