### ISSUE TITLE
Showing some warning in users2fa

### ISSUE THREAD

**Issue by prakash76101** [rcschaff82/cwp_2fa#9]
Warning: Invalid argument supplied for foreach() in /usr/local/cwpsrv/htdocs/resources/admin/modules/user2fa.php on line 19

Notice: Undefined variable: userpost in /usr/local/cwpsrv/htdocs/resources/admin/modules/user2fa.php on line 62

Warning: Invalid argument supplied for foreach() in /usr/local/cwpsrv/htdocs/resources/admin/modules/user2fa.php on line 62

**Comment by rcschaff82** [comment]
Are there any user accounts on the panel?   Looking at the code, it grabs a list of users from the database.  If none exist, those errors will show.

Will look to suppress the errors in future update.
